(() => {
 'use strict';
 const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
 const assets=window.GAME_ASSETS||[], cards=assets.filter(x=>x.category!=='Arte');
 const details=window.CARD_DETAILS?.cards||{};
 let owned={};
 try{const stored=JSON.parse(localStorage.getItem('recom-cards')||'{}');if(window.CARD_PROGRESS.isMap(stored))owned=stored;}catch{}
 function kind(a){if(details[a.name])return details[a.name].collection;if(/ - [AM][0-9]*$/.test(a.name)||['Fake Attack Card','Keyblade','Honey Bee','Card Soldier, Spade','Marluxia (Second Form)','Marluxia (Third Form)'].includes(a.name))return 'opponent';if(['Wind','Honey'].includes(a.name))return 'minigame';return 'pending';}
 const kindLabel={sora:'Coleção de Sora',riku:'Deck de Riku',opponent:'Uso do adversário',minigame:'Carta de minigame',pending:'Ficha a catalogar'};
 const norm=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
 const searchable=text=>norm(text+' '+(window.GUIDE_I18N?.translate(text)||''));
 const find=name=>cards.find(x=>norm(x.name)===norm(name||''));
 const image=(a,cls='')=>{const im=new Image();im.src=a.file;im.alt=a.name;im.className=cls;im.loading='lazy';im.decoding='async';return im;};
 const toast=msg=>{const e=document.createElement('div');e.className='toast';e.role='status';e.textContent=msg;document.body.append(e);setTimeout(()=>e.remove(),4000);};
 const dialog=document.createElement('dialog');dialog.className='asset-dialog';dialog.innerHTML='<button class="close-dialog" aria-label="Fechar">×</button><div class="dialog-content"></div>';document.body.append(dialog);
 dialog.querySelector('button').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog)dialog.close();};
 function inspect(a){
  const d=details[a.name],k=kind(a),host=dialog.querySelector('.dialog-content');host.replaceChildren();dialog.classList.add('card-sheet');
  const visual=document.createElement('div');visual.className='sheet-visual';visual.append(image(a));const edition=document.createElement('small');edition.textContent='Re:Chain of Memories / HD';visual.append(edition);
  const body=document.createElement('div');body.className='sheet-body';const category=document.createElement('div');category.className='sheet-eyebrow';category.textContent=a.category+' / '+kindLabel[k];const title=document.createElement('h2');title.id='sheet-title';title.textContent=a.name;body.append(category,title);dialog.setAttribute('aria-labelledby','sheet-title');
  const paragraph=(label,text,cls='')=>{const block=document.createElement('div');block.className='sheet-block '+cls;const h=document.createElement('h4');h.textContent=label;const p=document.createElement('p');p.textContent=text;block.append(h,p);body.append(block);};
  if(d){
   const ability=document.createElement('p');ability.className='ability-name';ability.textContent=d.ability;body.append(ability);
   const stats=document.createElement('div');stats.className='sheet-stats';for(const [label,value] of [['DURAÇÃO',d.duration],['CUSTO',d.cp!==null?d.cp+' CP':k==='riku'?'Deck fixo de Riku':'CP varia por valor']]){const tile=document.createElement('div');const l=document.createElement('small');l.textContent=label;const v=document.createElement('strong');v.textContent=value;tile.append(l,v);stats.append(tile);}body.append(stats);
   paragraph('Efeito',d.effect);paragraph('Cuidados',d.warning,'sheet-warning');paragraph('Como obter / desbloquear',d.obtain);paragraph('Sugestão de uso',d.tip);
   if(a.category==='Inimigo')paragraph('Regra das cartas de inimigo','Uma ativação por carta a cada batalha; apenas um efeito de inimigo fica ativo por vez. Ativar outra carta substitui o efeito anterior. Durações em recargas também podem avançar ao usar itens de recarga.','sheet-rule');
   if(d.recipes){const wrap=document.createElement('div');wrap.className='sheet-recipes';for(const recipe of d.recipes){const row=document.createElement('div');row.className='recipe-row';recipe.cards.forEach((n,i)=>{if(i){const plus=document.createElement('span');plus.textContent='+';row.append(plus);}const item=find(n);if(item)row.append(image(item));});const name=document.createElement('strong');name.textContent='→ '+recipe.name;row.append(name);wrap.append(row);}body.append(wrap);}
   const own=document.createElement('button');own.className='own-card';own.type='button';const update=()=>{own.setAttribute('aria-pressed',Boolean(owned[a.name]));own.textContent=owned[a.name]?'✓ Já tenho esta carta':'＋ Marcar como obtida';};update();own.onclick=()=>{const next={...owned,[a.name]:!owned[a.name]};try{localStorage.setItem('recom-cards',JSON.stringify(next));owned=next;update();renderGallery();}catch{toast('Não foi possível salvar. Verifique o armazenamento do navegador.');}};body.append(own);
  }else paragraph('Sobre esta imagem',k==='opponent'?'Carta usada pelo adversário durante o combate. Esta variante não entra na lista de cartas obtidas do jogador.':k==='minigame'?'Carta de uso no minigame Bumble-Rumble. Fica separada das cartas que você equipa no deck de batalha.':'Esta família ainda não recebeu a ficha de efeitos. A imagem continua disponível para consulta; a marcação de coleção será liberada com a catalogação.');
  const refs=document.createElement('div');refs.className='sheet-sources';const links=d?[['Efeito e mecânicas',d.source],['Obtenção',d.obtainSource]]:[['Referência da imagem',a.source]];for(const [label,url] of links){const link=document.createElement('a');link.href=url;link.target='_blank';link.rel='noopener';link.textContent=label+' ↗';refs.append(link);}body.append(refs);host.append(visual,body);dialog.showModal();
 }
 function cardButton(a,label,value){const b=document.createElement('button');b.type='button';b.className='real-card';b.append(image(a));const name=document.createElement('span');name.textContent=label||a.name;b.append(name);if(value!==undefined){const v=document.createElement('span');v.className='example-value';v.textContent=value;b.append(v);}b.setAttribute('aria-label','Ampliar carta: '+a.name);b.onclick=()=>inspect(a);return b;}
 ['Kingdom Key','Cure','Oathkeeper','Fire','Oblivion'].forEach((n,i)=>{const a=find(n);if(!a)return;const im=image(a);im.loading='eager';im.style.setProperty('--angle',(-28+i*14)+'deg');$('#real-fan').append(im);});
 $('#asset-count').textContent=cards.length+' imagens';
 window.GUIDE_CARDS={open(name){const a=find(name);if(a)inspect(a);}};
 const icons=['⌂','↗','◇','＋','⚔','▣','♧','⌘','♜','◇','♧','ϟ','⚔','♟','♧','❀','☾','↻','!','♛'];
 $$('.index a:not(.library-brand)').forEach((a,i)=>{const ic=document.createElement('span');ic.className='nav-icon';ic.textContent=icons[i]||'◇';ic.ariaHidden='true';a.prepend(ic);});
 const menu=$('.menu-toggle');menu.onclick=()=>{const open=document.body.classList.toggle('nav-open');menu.setAttribute('aria-expanded',open);};
 document.addEventListener('click',e=>{if(document.body.classList.contains('nav-open')&&!e.target.closest('.index,.menu-toggle')){document.body.classList.remove('nav-open');menu.setAttribute('aria-expanded','false');}});
 function go(id){const i=window.PAGER.sections.findIndex(s=>s.id===id);if(i>=0)window.PAGER.show(i);document.body.classList.remove('nav-open');menu.setAttribute('aria-expanded','false');$('#search-results').hidden=true;$('#q').value='';}
 $$('.hero-actions a,.journey-strip a').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();go(a.hash.slice(1));}));
 $$('.index a').forEach(a=>a.addEventListener('click',()=>{document.body.classList.remove('nav-open');menu.setAttribute('aria-expanded','false');}));
 const typeMap={'c-atk':'Kingdom Key','c-mag':'Fire','c-sum':'Simba','c-itm':'Potion','c-fri':'Donald Duck','c-ene':'Shadow','c-map':'Tranquil Darkness','c-mapg':'Martial Waking','c-mapb':'Moogle Room','c-key':'Key of Beginnings','c-gim':'Gimmick Card','c-wld':'Traverse Town'};
 $$('.card').forEach(el=>{const key=Object.keys(typeMap).find(k=>el.classList.contains(k));const label=el.querySelector('.nm')?.textContent||'';const a=find(label==='Chefe'?'Guard Armor':typeMap[key]||'Kingdom Key');if(a)el.replaceWith(cardButton(a,label,el.querySelector('.val')?.textContent));});
 const aliases={'Pateta':'Goofy','Donald':'Donald Duck','Ataque':'Kingdom Key','Atq':'Kingdom Key','Gênio':'Genie','Gancho':'Captain Hook'};
 function matchText(text){const names=[...cards].sort((a,b)=>b.name.length-a.name.length);return names.find(a=>norm(text).includes(norm(a.name)))||Object.entries(aliases).map(([k,v])=>norm(text).includes(norm(k))?find(v):null).find(Boolean);}
 $$('.fdcard').forEach(el=>{const a=matchText(el.textContent);if(a){el.prepend(image(a));el.title=a.name;}});
 $$('.wcard').forEach(el=>{const world=el.querySelector('.wn').textContent;const a=cards.find(a=>a.category==='Mundo'&&(norm(world).includes(norm(a.name))||norm(a.name).includes(norm(world))));if(a)el.querySelector('summary').prepend(image(a,'world-thumb'));});
 $$('#bestiary tbody tr,#salas tbody tr').forEach(tr=>{const a=matchText(tr.cells[0].textContent);if(a)tr.cells[0].prepend(image(a,'tiny-card'));});
 $$('.boss').forEach(el=>{const a=matchText(el.querySelector('.bn')?.textContent||'');if(a)el.querySelector('header').prepend(image(a,'boss-card'));});
 $$('.fdcard img,.tiny-card,.boss-card').forEach(im=>{const a=cards.find(c=>c.file===im.getAttribute('src'));if(!a)return;const b=document.createElement('button');b.className='inline-card';b.type='button';b.setAttribute('aria-label','Ver ficha de '+a.name);im.replaceWith(b);b.append(im);b.onclick=()=>inspect(a);});
 const gallery=document.createElement('div');gallery.className='gallery-intro';gallery.innerHTML='<h3>O arquivo de cartas</h3><p>Conheça os efeitos, planeje seu deck e registre suas descobertas. Abra uma carta para ver sua ficha.</p><div class="collection-overview" aria-live="polite"></div><div class="gallery-tools"><input id="card-search" type="search" placeholder="Nome, efeito ou habilidade…" aria-label="Buscar carta no acervo"><select id="card-category" aria-label="Categoria de carta"><option value="">Todas as famílias</option></select><select id="card-status" aria-label="Filtrar coleção"><option value="detailed">Com ficha de efeitos</option><option value="all">Todo o acervo</option><option value="sora">Coleção de Sora</option><option value="riku">Deck de Riku</option><option value="owned">Já tenho</option><option value="missing">Faltam obter</option><option value="reference">Adversário / minigame</option><option value="pending">Ainda sem ficha</option></select></div><div class="gallery-meta" aria-live="polite"></div><div class="gallery-grid"></div><p class="footnote">Acompanhamento parcial: cartas de inimigo, magia e item com ficha nesta edição. Não equivale ao percentual do diário do jogo. As marcações são manuais e ficam salvas neste navegador.</p>';
 $('#cartas .sec-head').after(gallery);
 [...new Set(cards.map(c=>c.category))].forEach(c=>{const opt=document.createElement('option');opt.value=c;opt.textContent=c;$('#card-category').append(opt);});
 function renderGallery(){
  const term=norm($('#card-search').value),cat=$('#card-category').value,status=$('#card-status').value;
  const filtered=cards.filter(c=>{const d=details[c.name],k=kind(c);const match=status==='all'||(status==='detailed'&&d)||(status===k)||status==='owned'&&d&&owned[c.name]||status==='missing'&&d&&!owned[c.name]||status==='reference'&&['opponent','minigame'].includes(k);return match&&(!cat||c.category===cat)&&[c.name,d?.ability,d?.effect,d?.tag,d?.obtain].filter(Boolean).map(searchable).join(' ').includes(term);});
  $('.gallery-grid').replaceChildren(...filtered.map(a=>{const b=cardButton(a);b.dataset.card=a.name;const d=details[a.name];const state=document.createElement('small');state.className='card-status '+(owned[a.name]&&d?'is-owned':'');state.textContent=d?(owned[a.name]?'✓ Obtida':'○ Falta obter'):kindLabel[kind(a)];b.append(state);if(d){const effect=document.createElement('span');effect.className='card-effect';effect.textContent=d.ability;const blurb=document.createElement('small');blurb.className='card-blurb';blurb.textContent=d.effect;b.append(effect,blurb);}return b;}));
  $('.gallery-meta').textContent=filtered.length+' resultado'+(filtered.length!==1?'s':'')+' · '+cards.length+' imagens no acervo'+(!filtered.length?' · Tente outro filtro.':'');
  const sora=Object.keys(details).filter(n=>details[n].collection==='sora'),riku=Object.keys(details).filter(n=>details[n].collection==='riku');$('.collection-overview').textContent='SORA  '+sora.filter(n=>owned[n]).length+' / '+sora.length+'  ·  RIKU  '+riku.filter(n=>owned[n]).length+' / '+riku.length+'  ·  '+Object.keys(details).length+' fichas de efeitos';
 }
 $('#card-search').oninput=renderGallery;$('#card-category').onchange=renderGallery;$('#card-status').onchange=renderGallery;renderGallery();
 const combat=$('#combate svg');if(combat){const box=document.createElement('div');box.className='combat-demo';const k=find('Kingdom Key'),f=find('Fire');if(k&&f){box.append(cardButton(k,'Sua carta',8));const mid=document.createElement('span');mid.textContent='8 > 5';box.append(mid,cardButton(f,'Carta inimiga',5));const msg=document.createElement('small');msg.textContent='CARD BREAK\nO maior valor interrompe a ação.';box.append(msg);combat.replaceWith(box);}}
 const search=document.createElement('div');search.id='search-results';search.className='search-results';search.hidden=true;search.setAttribute('aria-label','Resultados da busca');$('.bar-in').append(search);
 // Search reads text only, keeping existing controls and their listeners intact.
 const sections=window.PAGER.sections;
 $('#q').addEventListener('input',()=>{const raw=$('#q').value.trim(),term=norm(raw);search.replaceChildren();search.hidden=term.length<2;if(search.hidden)return;let count=0;
  cards.filter(a=>{const d=details[a.name];return d&&[a.name,d.ability,d.effect].map(searchable).join(' ').includes(term);}).slice(0,8).forEach(a=>{const b=document.createElement('button');const title=document.createElement('strong');title.textContent='Carta · '+a.name;const p=document.createElement('small');p.textContent=details[a.name].effect;b.append(title,p);b.onclick=()=>{go('cartas');inspect(a);};search.append(b);count++;});
  sections.forEach(section=>{const text=section.textContent.replace(/\s+/g,' ');const at=norm(text).indexOf(term);if(at<0)return;const b=document.createElement('button');const title=document.createElement('strong');title.textContent=section.querySelector('h2').textContent;const excerpt=document.createElement('small');excerpt.textContent='…'+text.slice(Math.max(0,at-40),at+115)+'…';b.append(title,excerpt);b.onclick=()=>go(section.id);search.append(b);count++;});if(!count){const p=document.createElement('p');p.textContent='Nenhuma memória encontrada. Tente outro termo.';search.append(p);}});
 $('#q').addEventListener('keydown',e=>{if(e.key==='Escape')search.hidden=true;if(e.key==='ArrowDown'){e.preventDefault();search.querySelector('button')?.focus();}if(e.key==='Enter')search.querySelector('button')?.click();});
 document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();$('#q').focus();}if(e.key==='Escape'){search.hidden=true;document.body.classList.remove('nav-open');menu.setAttribute('aria-expanded','false');}});
 document.addEventListener('click',e=>{if(!e.target.closest('.search-results,.searchwrap'))search.hidden=true;});
 function progress(){const all=$$('#ach input[type=checkbox]'),n=all.filter(x=>x.checked).length;$('#overview-count').textContent=n+' / '+all.length;$('#overview-fill').style.width=(n/all.length*100)+'%';}
 document.addEventListener('change',progress);$('#reset')?.addEventListener('click',progress);progress();
 const save=document.createElement('div');save.innerHTML='<div class="save-tools"><button id="export-save">↓ Exportar progresso</button><button id="import-save">↑ Importar progresso</button><input id="save-file" type="file" accept="application/json,.json" hidden></div><p class="backup-note">Seu progresso é salvo neste navegador. Exporte uma cópia para levar seus checklists a outro computador.</p>';
 $('#conquistas .sec-head').after(save);
 const keys=window.CARD_PROGRESS.keys;
 $('#export-save').onclick=()=>{const data={version:2,game:'recom',savedAt:new Date().toISOString(),data:{}};try{keys.forEach(k=>data.data[k]=JSON.parse(localStorage.getItem(k)||'{}'));window.CARD_PROGRESS.validateBackup(data,Object.keys(details));}catch{toast('Não foi possível ler o progresso.');return;}const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='memorias-progresso-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);toast('Backup com checklists e coleção exportado.');};
 $('#import-save').onclick=()=>$('#save-file').click();
 $('#save-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>1000000)throw Error();const input=JSON.parse(await f.text());const data=window.CARD_PROGRESS.validateBackup(input,Object.keys(details));const host=dialog.querySelector('.dialog-content');host.replaceChildren();dialog.classList.remove('card-sheet');dialog.removeAttribute('aria-labelledby');const h=document.createElement('h3');h.textContent='Restaurar suas memórias?';const p=document.createElement('p');p.textContent=Object.hasOwn(data,'recom-cards')?'Este backup substituirá seus checklists e sua coleção de cartas.':'Backup antigo: substitui os checklists e mantém sua coleção de cartas atual.';const b=document.createElement('button');b.className='primary';b.textContent='Restaurar progresso';b.onclick=()=>{try{window.CARD_PROGRESS.restore(localStorage,data);location.reload();}catch{dialog.close();toast('Não foi possível salvar neste navegador.');}};host.append(h,p,b);dialog.showModal();}catch{toast('Arquivo inválido. Escolha um backup exportado pelo guia.');}e.target.value='';};
 const note=document.createElement('p');note.className='footnote';note.innerHTML='Cartas, decks e a nova rota de progressão têm referências nas respectivas seções. As faixas de nível são sugestões editoriais para Proud. Parte do roteiro original e das conquistas ainda aguarda revisão completa para Steam.';$('#comecar').append(note);
 // Persist the last visited chapter without interfering with explicit links.
 const show=window.PAGER.show;window.PAGER.show=function(i,opts){show(i,opts);try{localStorage.setItem('recom-chapter',sections[i]?.id||'comecar');}catch{}};
 if(!location.hash){try{const id=localStorage.getItem('recom-chapter');const i=sections.findIndex(s=>s.id===id);if(i>=0)window.PAGER.show(i,{noScroll:true});}catch{}}
 const chapterObserver=new MutationObserver(()=>{const visible=sections.filter(s=>!s.hidden);if(visible.length===1)try{localStorage.setItem('recom-chapter',visible[0].id);}catch{}});sections.forEach(s=>chapterObserver.observe(s,{attributes:true,attributeFilter:['hidden']}));
 let printDetails=[];
 window.addEventListener('beforeprint',()=>{printDetails=$$('details').map(d=>[d,d.open]);printDetails.forEach(([d])=>d.open=true);});
 window.addEventListener('afterprint',()=>printDetails.forEach(([d,open])=>d.open=open));
})();
