(() => {
 'use strict';
 const wiki=n=>'https://www.khwiki.com/'+n;
 const community='https://steamcommunity.com/app/2552430/discussions/0/597414796439061224/';
 const hybridSource='https://www.reddit.com/r/KingdomHearts/comments/1ajjcvx/kh_recom_what_are_some_good_decks_for_the_13th/';
 const c=(name,value=7)=>({name,value});
 const A=()=>c('Kingdom Key'),B=()=>c('Three Wishes'),C=()=>c('Lady Luck'),S=()=>c('Stop',6);
 const presets=[
 {id:'ice',name:'Blizzaga',stage:'INÍCIO',icon:'❄',subtitle:'Controle de grupos',unlock:'Assim que reunir três Blizzard.',groups:[[c('Blizzard',6),c('Blizzard',6),c('Blizzard',6)]],combo:'Blizzaga',passive:'Blue Rhapsody',item:'Ether',play:'Mantenha os inimigos à frente e use os trios de Blizzard. Comece com poucas repetições e acrescente mais conforme seu CP permitir.',limit:'Evite inimigos que absorvem ou anulam gelo. Depois da recarga normal, os trios deixam de estar completos; Ether comum não restaura as Blizzard perdidas.',source:wiki('Blizzard'),community},
 {id:'fire',name:'Firaga',stage:'CHEFES',icon:'♨',subtitle:'Pressão à distância',unlock:'Três Fire; Red Nocturne é um reforço opcional.',groups:[[c('Fire',6),c('Fire',6),c('Fire',6)]],combo:'Firaga',passive:'Red Nocturne',item:'Mega-Ether',play:'Dispare os trios de Fire em um alvo vulnerável ao fogo. É uma estratégia relatada contra Vexen; mantenha espaço para curar e quebrar os ataques dele.',limit:'Não use contra Axel ou inimigos imunes ao fogo. Ser uma estratégia útil contra Vexen não significa que ele tenha fraqueza elemental a fogo no remake. Sem Mega-Ether, terá menos repetições disponíveis.',source:wiki('Fire'),community},
 {id:'sonic',name:'Sonic Blade',stage:'NÍVEL 27+',icon:'ϟ',subtitle:'Pressão em alvos no chão',unlock:'Aprender Sonic Blade a partir do nível 27.',groups:[[A(),B(),C()]],combo:'Sonic Blade',passive:'Jafar (Genie)',item:'Hi-Potion',play:'Use três tipos diferentes de ataque, somando 20–23. Aqui, 7 + 7 + 7 = 21. Acerte os comandos de continuação no tempo certo; use Hi-Potion para recuperar os ataques perdidos.',limit:'Erros no tempo ou investidas que não acertam interrompem a sequência. Alvos aéreos e evasivos exigem outra abordagem. Pode substituir as Keyblades, mantendo três tipos distintos e a soma correta.',source:wiki('Sonic_Blade'),community},
 {id:'frame',name:'Lethal Frame',stage:'NÍVEL 32+',icon:'◷',subtitle:'Uma janela para punir',unlock:'Aprender Lethal Frame a partir do nível 32 e obter Stop.',groups:[[S(),A(),B()]],combo:'Lethal Frame',passive:'Jafar (Genie)',item:'Mega-Ether',play:'Aproxime-se do alvo antes de usar Stop + ataque + ataque. O exemplo soma 20 para dificultar que o estoque seja quebrado. Jafar ajuda a proteger a abertura.',limit:'A abertura de cerca de três segundos pode ser interrompida sem proteção. Distância e posição prejudicam o resultado. Stop é a carta perdida: Hi-Potion não a recupera. Jafar tem duração limitada.',source:wiki('Lethal_Frame'),community:hybridSource},
 {id:'hybrid',name:'Lethal → Sonic',stage:'AVANÇADO',icon:'⇄',subtitle:'Dois planos no mesmo deck',unlock:'Aprender os dois sleights; ter Stop e três tipos de ataque.',groups:[[S(),A(),B()],[S(),C(),A()],[S(),B(),C()]],combo:'Lethal Frame',passive:'Jafar (Genie)',item:'Elixir',play:'Execute os três Lethal Frame na ordem mostrada. Na recarga normal, os Stop somem e as seis cartas de ataque restantes formam dois Sonic Blade. Alterne a visualização abaixo para entender a transformação.',limit:'Demonstração da primeira recarga do núcleo, com cartas normais. Pressupõe usar cada trio uma vez, sem misturar cura ou itens, e sem efeitos que alterem o consumo. Elixir restaura a formação inicial; não o use antes da transformação demonstrada.',source:wiki('Lethal_Frame'),community:hybridSource},
 {id:'flare',name:'Mega Flare',stage:'NÍVEL 57+',icon:'✦',subtitle:'Limpeza para farm',unlock:'Aprender Mega Flare a partir do nível 57. Mushu: primeira recompensa de Room of Rewards em Hollow Bastion.',groups:[[c('Mushu',6),c('Fire',6),c('Fire',6)]],combo:'Mega Flare',passive:'Red Nocturne',item:'Mega-Ether',play:'Mushu + Fire + Fire produz dano de fogo em área. A comunidade usa essa combinação para acelerar batalhas de EXP, especialmente em Destiny Islands. Ative Red Nocturne antes de começar.',limit:'Não resolve inimigos imunes a fogo, como Wizard. Leve ataques alternativos se a sala puder contê-los. Mushu sai primeiro do estoque; precisa de recuperação de magia perdida para repetir o núcleo inteiro.',source:wiki('Mega_Flare'),community:'https://www.reddit.com/r/KingdomHearts/comments/1d21ao2'}
 ];
 let active=presets[0],repeats=3,after=false;
 const host=document.getElementById('deck-detail');if(!host)return;
 function element(tag,text,cls){const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;}
 function card(x){const b=element('button',null,'lab-card');b.type='button';b.setAttribute('aria-label','Ver ficha de '+x.name);const asset=window.GAME_ASSETS.find(a=>a.name===x.name);if(asset){const im=element('img');im.src=asset.file;im.alt='';im.loading='lazy';b.append(im);}b.append(element('strong',x.name));if(x.value!==undefined)b.append(element('span',String(x.value),'lab-value'));b.onclick=()=>window.GUIDE_CARDS.open(x.name);return b;}
 function groupsFor(p,n,reload){let groups=Array.from({length:n},()=>p.groups).flat();if(reload){const left=groups.flatMap(g=>g.slice(1));groups=Array.from({length:left.length/3},(_,i)=>left.slice(i*3,i*3+3));}return groups;}
 function render(){
  host.replaceChildren();const head=element('div',null,'lab-heading');head.append(element('small',active.stage),element('h3',active.name),element('p',active.unlock));host.append(head);
  const facts=element('div',null,'lab-facts');for(const [label,txt] of [['Como jogar',active.play],['Onde perde força',active.limit]]){const block=element('div');block.append(element('h4',label),element('p',txt));facts.append(block);}host.append(facts);
  const controls=element('div',null,'lab-controls');const label=element('label','Repetições do núcleo ');const select=element('select');select.setAttribute('aria-label','Repetições do núcleo');[1,2,3,4].forEach(n=>{const o=element('option',String(n));o.value=n;o.selected=n===repeats;select.append(o);});select.onchange=()=>{repeats=Number(select.value);render();};label.append(select);controls.append(label);
  if(active.id==='hybrid'){const phase=element('button',after?'↶ Ver primeira passagem':'⇄ Simular recarga normal','phase-button');phase.type='button';phase.setAttribute('aria-pressed',after);phase.onclick=()=>{after=!after;render();host.querySelector('.phase-button').focus();};controls.append(phase);}host.append(controls);
  const groups=groupsFor(active,repeats,after);const status=element('p',`${groups.length} × ${after?'Sonic Blade':active.combo} · ${groups.flat().length} cartas no núcleo`,'lab-status');status.setAttribute('aria-live','polite');host.append(status);
  if(after)host.append(element('p',`${repeats*3} Stop saíram da recarga. Leia os ataques restantes da esquerda para a direita.`,'reload-note'));
  const sequence=element('div',null,'lab-sequence');groups.forEach((g,i)=>{const row=element('div',null,'lab-trio');row.append(element('small',`${String(i+1).padStart(2,'0')} / ${after?'Sonic Blade':active.combo} · soma ${g.reduce((s,x)=>s+x.value,0)}`));const line=element('div',null,'lab-cards');g.forEach(x=>line.append(card(x)));row.append(line);sequence.append(row);});host.append(sequence);
  const support=element('div',null,'lab-support');support.append(element('h4','Depois do núcleo: apoio sugerido'),element('p','3 Cure para Curaga, 1 item de recuperação e 2 ataques 0 normais no fim. Reserve a cura e os zeros para a hora certa. Valores de exemplo; o custo total depende das cartas que você possui.'));
  const line=element('div',null,'support-cards');[c('Cure',6),c('Cure',6),c('Cure',6),c(active.item,8),c('Kingdom Key',0),c('Kingdom Key',0)].forEach(x=>line.append(card(x)));support.append(line,element('h4','Carta de inimigo opcional — ativação separada'),card({name:active.passive}));host.append(support);
  const refs=element('p',null,'lab-sources');[['Mecânica e desbloqueio',active.source],['Relato da comunidade',active.community]].forEach(([label,url])=>{const a=element('a',label+' ↗');a.href=url;a.target='_blank';a.rel='noopener';refs.append(a);});host.append(refs);
  document.querySelectorAll('#deck-picker button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.id===active.id));
 }
 presets.forEach(p=>{const b=element('button',null,'deck-choice');b.type='button';b.dataset.id=p.id;b.append(element('span',p.icon),element('small',p.stage),element('strong',p.name),element('em',p.subtitle));b.onclick=()=>{active=p;after=false;repeats=p.id==='hybrid'?1:3;render();};document.getElementById('deck-picker').append(b);});render();
 window.DECK_LAB={presets,groupsFor};
})();

