(() => {
 'use strict';
 const data=window.ROUTE_DATA, $=s=>document.querySelector(s);
 const make=(tag,text,cls)=>{const e=document.createElement(tag);if(text)e.textContent=text;if(cls)e.className=cls;return e;};
 const storageKey='recom-route-preferences';
 let side='riku',floor='',level='',order={riku:data.riku.map(x=>x.world),sora:data.sora.map(x=>x.world)};
 try{const p=JSON.parse(localStorage.getItem(storageKey)||'null');if(p){if(['riku','sora'].includes(p.side))side=p.side;if(data[side].some(r=>r.floor===p.floor))floor=p.floor;if(Number.isInteger(p.level)&&p.level>=1&&p.level<=99)level=p.level;for(const s of ['riku','sora'])if(Array.isArray(p.order?.[s])&&p.order[s].length===data[s].length&&new Set(p.order[s]).size===data[s].length&&p.order[s].every((w,i)=>data[s][i].options.includes(w)))order[s]=p.order[s];}}catch{}
 const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify({side,floor,level:Number(level)||null,order}));}catch{}};
 function card(name){const a=window.GAME_ASSETS.find(x=>x.name===name);const b=make('button',null,'route-card');b.type='button';b.setAttribute('aria-label','Ver carta '+name);if(a){const im=make('img');im.src=a.file;im.alt='';im.loading='lazy';b.append(im);}b.append(make('span',name));b.onclick=()=>window.GUIDE_CARDS.open(name);return b;}
 function options(){const select=$('#route-floor');select.replaceChildren();const empty=make('option','Escolha seu andar');empty.value='';select.append(empty);data[side].forEach(r=>{const o=make('option',r.floor);o.value=r.floor;select.append(o);});select.value=floor;}
 function advice(){const el=$('#route-advice'),i=data[side].findIndex(r=>r.floor===floor);el.replaceChildren();if(i<0){el.append(make('p','Escolha o andar para ver sua meta e a estratégia do mundo. A tabela completa está logo abaixo.'));return;}
  const r=data[side][i],world=order[side][i];const num=Number(level);let msg='Informe seu nível para comparar com a faixa recomendada.';
  if(world==='100 Acre Wood')msg='Sem meta de combate aqui. Faça os minigames e siga a história.';
  else if(level!==''&&(!Number.isInteger(num)||num<1||num>99))msg='Digite um nível inteiro entre 1 e 99.';
  else if(level!=='')msg=num<r.low?`Você está abaixo da referência de ${r.low}–${r.high}. Faça os encontros do caminho; só repita salas se o combate estiver difícil. Estar abaixo da faixa não bloqueia a progressão.`:num>r.high?'Você já passou da faixa de conforto. Avance na história; não precisa limpar todas as salas por EXP.':`Você está na faixa de ${r.low}–${r.high}. Se tem cura e cartas de mapa, tente o chefe; não precisa buscar o topo da faixa.`;
  el.append(make('strong',`${side==='riku'?'Riku':'Sora'} · ${floor} · ${world}`),make('p',msg));
 }
 function detail(){const host=$('#route-selected');host.replaceChildren();const i=data[side].findIndex(r=>r.floor===floor);if(i<0)return;const row=data[side][i],name=order[side][i],w=data.worlds[name];const box=make('article',null,'route-world');const header=make('div',null,'route-world-head');header.append(card(name),make('h3',`${floor} / ${name}`),make('span',name==='100 Acre Wood'?'Sem combate':`Meta antes da saída: ${row.low}–${row.high}`,'route-level-tag'));box.append(header);
  const grid=make('div',null,'route-world-grid');const enemies=make('div');enemies.append(make('h4','Alvos para os encontros do caminho'));const line=make('div',null,'route-enemies');w.targets.forEach(n=>line.append(card(n)));enemies.append(line,make('p',w.targets.length?'Reconheça as espécies. A figura na exploração não garante todas as ondas.':'Não há Heartless para farmar neste mundo.','route-caption'));grid.append(enemies);
  const strategy=make('div');strategy.append(make('h4','Como fazer'),make('p',w[side]),make('h4','Não desperdice tempo'),make('p',w.avoid));grid.append(strategy);box.append(grid);
  if(w.room){const room=make('div',null,'route-room');room.append(card(w.room),make('p',`Sala sugerida para testar: ${w.room}. Se já está confortável para o chefe, poupe a carta e avance.`));box.append(room);}box.append(make('p',row.checkpoint,'route-checkpoint'));if(side==='sora')box.append(make('p','Level up: aprenda os sleights úteis; aumente CP para caber o núcleo, cura e zeros. Escolha HP se sua margem de erro estiver pequena. Nível alto sozinho não corrige um deck mal organizado.'));host.append(box);
 }
 function table(){const body=$('#route-rows');body.replaceChildren();data[side].forEach((r,i)=>{const tr=make('tr');if(r.floor===floor)tr.className='current-floor';const td=make('td'),button=make('button',r.floor,'floor-link');button.type='button';button.setAttribute('aria-label','Ver estratégia de '+r.floor);button.onclick=()=>{floor=r.floor;$('#route-floor').value=floor;save();render();$('#route-selected').scrollIntoView({block:'start'});};td.append(button);tr.append(td);const world=make('td');if(r.options.length>1){const s=make('select');s.setAttribute('aria-label',`Mundo de ${r.floor}`);r.options.forEach(n=>{const o=make('option',n);o.value=n;s.append(o);});s.value=order[side][i];s.onchange=()=>{const next=s.value,other=order[side].indexOf(next);[order[side][i],order[side][other]]=[order[side][other],order[side][i]];save();render();};world.append(s);}else world.textContent=order[side][i];tr.append(world,make('td',order[side][i]==='100 Acre Wood'?'Sem meta de combate':`${r.low}–${r.high}`),make('td',r.floor===(side==='riku'?'B1':'13F')?'Tentar o final; 99 depois':'Avançar se estiver confortável'));body.append(tr);});}
 function render(){advice();detail();table();}
 $('#route-side').value=side;$('#route-level').value=level;options();render();
 $('#route-side').onchange=e=>{side=e.target.value;floor='';level='';$('#route-level').value='';options();save();render();};$('#route-floor').onchange=e=>{floor=e.target.value;save();render();};$('#route-level').oninput=e=>{level=e.target.value;save();advice();};
 document.querySelectorAll('.route-link').forEach(a=>a.onclick=e=>{e.preventDefault();window.PAGER.show(window.PAGER.sections.findIndex(s=>s.id==='nivel'));});
 $('#xp-compare').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);const xa=Number(f.get('xpA')),xb=Number(f.get('xpB')),ta=Number(f.get('timeA')),tb=Number(f.get('timeB'));const out=$('#xp-result');if(![xa,xb,ta,tb].every(n=>Number.isFinite(n)&&n>0)){out.textContent='Use valores positivos nos dois testes.';return;}const a=xa/ta,b=xb/tb,na=f.get('nameA').trim()||'Teste A',nb=f.get('nameB').trim()||'Teste B';out.textContent=`${na}: ${Math.round(a).toLocaleString('pt-BR')} EXP/min. ${nb}: ${Math.round(b).toLocaleString('pt-BR')} EXP/min. `+(Math.abs(a-b)<.01?'Empate neste teste.':`${a>b?na:nb} rendeu ${((Math.max(a,b)/Math.min(a,b)-1)*100).toFixed(1).replace('.',',')}% mais neste teste.`)+' Repita se as ondas foram muito diferentes.';};
})();
